.env.example
docs/contributing.md
readme.md
src/db/routes/mod.rs
src/db/server.rs
src/db/utils/response.rs
src/main.rs
tests/common/mod.rs
tests/test_server.rs

This PR adds a layer of HTTP authentication before performing actions to the database via the endpoints. This authentication is applied only for `/index` and `/values` routes.
This PR add a feature that will get `x-oasysdb-token` header from the request and match it against the `OASYSDB_TOKEN` environment variable used to run the server. If the token doesn't match, the server will return a 401 unauthorized response.
I tested this PR by running `cargo test` and manually checking functionality by calling the endpoints directly from Insomnia. There is no new tests being added to the test suite. But, I added functionality to the existing tests to guard for unauthorized request without or invalid `x-oasysdb-token`.

feat: token-based authentication

---

src/db/mod.rs
src/db/routes/index.rs
src/db/routes/mod.rs
src/db/routes/values.rs
src/db/server.rs
src/lib.rs
src/main.rs
tests/common/mod.rs

This PR solves the issue where the server doesn't acccept multiple connections/requests at once. It will throw connection refused error or even sometimes crash the server.
1. I modified the server in a way to prevent direct mutation to the server by using `Arc` and `Mutex` for shared values.
2. I fixed the `tokio::spawn` code which is the primary source of this problem.
3. I remove the `Server.serve()` function and replace it with a standalone `serve` function that will handle the server and thread creation. In this function, the server is wrapped by `Arc` to allow threads to refer to the same server.
I have modified the test suite to accomodate the changes that I made to the server functionality.
I tested this PR by using a custom Python script to create a multi-threaded request to the …

fix: fix server multithreading

---

src/db/routes/values.rs

This PR will remove returning the value which contains embedding and data when creating a new key-value pair because it's redundant. For high-dimensional embeddings, this will cause extra overhead to write response back to the client.
Delete the part of code that constructs and returns the body for the response. Instead, we return `None` for the body with code 201 which is the same as previously.
I have tested this PR manually using Insomnia to make a request to POST `/values` which after this change will return an empty object.

fix: post values remove response body

---

.env.example
src/db/utils/stream.rs

This PR introduce a flexible configuration to configure read buffer for the TCP stream. It was initially set on 1024 which is not enough to read full length body of high-dimensional embeddings (tested using 512 and 1536 dimensions embedding).
Added an environment variable `OASYSDB_BUFFER_SIZE` that will define the read buffer size for when reading data from stream. By default, this is set to 32768 (enough to read 1536 dimension embedding created by Python `random.random()` function).
This environment variable allows users who use lower dimensional embedding to set the buffer size lower to optimize the performance.
Tested this PR using a Python script to generate the embedding and calling the `POST /values` endpoint to create a new value. I didn't add anything to the test suite as making a …

fix: increase read buffer

---

.env.example
.gitignore
Cargo.lock
Cargo.toml
readme.md
src/db/server.rs
src/main.rs
tests/common/mod.rs
tests/test_server.rs

This PR will replace OasysDB HashMap key-value store that doesn't persist with `sled` embeddable database that persist. There might be a trade-off in the performance but I haven't test anything related with this yet.
Sled is an embeddable key-value database that is ACID compliant making it a suitable option to persist data of OasysDB. For more information about Sled, check out their [GitHub repo](https://github.com/spacejam/sled) or [Rust docs](https://docs.rs/sled/latest/sled/index.html).
Although it's not the best option to add more dependencies, Sled is a pretty decent option that we have to achieve great persistance with minimal time investment.
I have tried creating a append-only log from scratch using commitlog crate but I encounter a roadblock and unable to resolve it even after …

feat: database persistence

---

docs/contributing.md
readme.md
src/api/graphs.rs
src/db/database.rs
src/tests/mod.rs
src/tests/test_graphs.rs

This PR introduce a feature that allows users to filter the data while building a graph. This allows building a graph with a specific set of values. This is useful to support multiple custom graph in the same database.
For example, if we have data with type image or text, we can have one graph for image type only and another one for text type only.
We simply iterate over the filters which now is included in the data to build the graph, the graph configuration data. Then, we match if the values that we want to use to build a graph match any of the filter. If it is, we include it in the values used to build graph.
I have tested the functionality locally with an HTTP client to create multiple values with 2 different IDs and used this functionality to create 2 different graph for each ID.

feat: graph build allow data filter

---

src/api/graphs.rs
src/api/values.rs
src/db/database.rs
src/lib.rs
src/tests/test_graphs.rs
src/tests/test_values.rs

The purpose of this PR is to add endpoints to reset the database as described in issue #13. There are 2 endpoints added, one to reset the values database and the other is to reset the graphs database.
I simply add 2 new database method which the underlying storage engine, Sled, already provided by default. Then, I add 2 new endpoints respectively to reset the graphs and the values.
I added 2 new unit tests to test the newly added functionality.

feat: add reset endpoints

---

.gitignore
Cargo.lock
Cargo.toml
bench/main.rs
bench/utils.rs
readme.md
src/func/collection.rs

This PR adds a benchmark for search/query functionality of the vector collection. This benchmark uses SIFT10K dataset by default but can be reconfigured for larger datasets. All of the datasets is available on http://corpus-texmex.irisa.fr.
I added several crates that helps with benchmarking:
- `criterion`: Benchmarking.
- `byteorder`: Reading the benchmark dataset.
- `tar` `flate2`: Extracting the dataset.
- `curl` `tokio`: Downloading the dataset.
This PR is created to download the SIFT10K dataset before running `cargo bench` if the dataset doesn't exist. This helps simplified the benchmarking process.
This PR can be tested by simply running the `cargo bench` command. No additional test needed as this PR only introduced benchmarking functionality.

chore: add benchmark

---

Cargo.lock
Cargo.toml
examples/extract-metadata.rs
readme.md
src/func/mod.rs
src/lib.rs
src/prelude/mod.rs

This PR solves an issue where user is unable to access the value inside of the `Metadata` since it's not a public module. With this use case, users can access the value inside the `Metadata` using the `match` statement.
This PR makes `Metadata` public and add a `prelude` module that allows users to import OasysDB structs, enums, and types using `use oasysdb::prelude::*;` instead of importing modules separately.
No additional functionality needed beside adding the `prelude` imports which is tested via `cargo test`.

fix: make metadata public

---

src/func/collection.rs

This PR solves an issue where user use `typed-builder` , the `Collection` class do not implement `Debug`
This PR makes `Collection` and `Config` implement `Debug`
How did you test this PR? Please provide a description of the tests that you ran to verify your changes.
How should the reviewer test this PR? If applicable, have you added tests to cover your changes?

fix: implement debug trait for collection & config

---

.github/workflows/quality-check.yml

Since we are creating a Python binding to allow OasysDB to be used from Python projects, we need a way to automate the testing process of the Python interoperability to make sure that everything is usable from both Rust and Python. So, this PR adds a new jobs to the CI to run `pytest`.
This PR uses `PyO3/maturin-action` to build OasysDB wheels that is usable and testable. Then the CI will setup the Python environment and run `pytest` against the `py/tests` directory of the project.
This is a CI changes without any additional feature on the codebase added.

ci: add pytest gh action

---

py/oasysdb/collection.pyi
py/tests/test_collection.py
src/func/collection.rs
src/tests/test_collection.rs

This API introduces a new API to the `Collection` as defined below. This API will return all of the records contain in the collection in the form of a HashMap of the Vector ID as a primitive type of `usize` and `Record` which contains vector and metadata.
```rs
pub fn list(&self) -> Result<HashMap<usize, Record>, Error> {...}
```
Currently, this adds a very barebone approach of doing this without other utility functionality like pagination or return limit.
I have added a test for each `cargo test` and `pytest` to test this implementation.

feat: add list api

---

examples/quickstart.rs
py/example.py
py/oasysdb/collection.pyi
py/tests/test_collection.py
readme.md
src/func/collection.rs
src/func/distance.rs
src/func/mod.rs
src/func/utils.rs
src/lib.rs
src/prelude/mod.rs
src/tests/mod.rs
src/tests/test_collection.rs
src/tests/test_database.rs
src/tests/test_distance.rs

With the new feature that allows users to customize the distance formula used for the collection indexing, this PR adds documentation on how to configure it both from Python and Rust project. This PR also changes the implementation in a way that allows the use of `Distance` enum from Rust project while in Python, users can just set the distance using string.
This PR also adds getters and setters function to improve the usage from Python codebase.
I have modified the test suite to fit the new implementations.

chore: add docs and refactor

---

py/oasysdb/collection.pyi
py/tests/test_collection.py
src/func/collection.rs
src/func/distance.rs
src/tests/test_collection.rs

This PR adds a new configuration to the `Collection` struct, `relevancy` a threshold score that guards irrelevant neighbor candidates from being included into the search result. By default, it is set to -1.0 which deactivates the relevancy checks. This value can be change as needed to fine-tune the exact threshold of relevance.
To use it:
```rs
// ...
collection.relevancy = 0.3
```
Because we have 3 `Distance` options that users can configure, I implement a check where for Euclidean distance, the distance of vector considered relevant is smaller than the relevancy score. For Dot or Cosine distance, the distance between vectors should be larger than the relevancy score.
I have modified the test of search collection to include assert statements to check the search result against the …

feat: result relevancy threshold

---

py/oasysdb/collection.pyi
py/tests/test_collection.py
src/func/collection.rs
src/tests/mod.rs
src/tests/test_collection.rs

This PR adds a new method to the `Collection` struct to insert multiple vector records at once. The implementation of this method is dedicated and optimized for inserting multiple vector records instead of a wrapper of the insert method with loop.
I have added a new test suite for both the functionality in Rust and Python testing inserting many vector records at once.

feat: add batch insert

---

src/func/collection.rs

Return the `VectorID` of the new vector record after the inserts.
Straightforward and small scope functionality added.

feat: return new vectorid after insert

---

src/func/collection.rs
src/func/distance.rs
src/func/err.rs

In addition to resolving issue #45, this PR improves the overall implementation of OasysDB native error type. This PR introduce a new field to the error struct, `kind`. This field represents the type/source of error happening in OasysDB.
There is no new functionality added.

feat: improve error type implementation

---

py/oasysdb/collection.pyi
py/tests/test_collection.py
src/func/collection.rs

This PR:
- Change the `ml` field default value for `Config` from 0.3 to 0.2885 which is closer to the optimal value of `1/ln(M)` where M is 32.
- Add `default()` method to Python as an alias for `create_default()`.

fix: improve config

---

src/func/err.rs

Please check issue  #68 for more information about this PR.
To test this functionality:
1. Create a function that returns `anyhow::Result`.
2. Use any method that returns OasysDB native error, `Result<_, Error>`, such as `Collection.build` method.
3. Test propagate OasysDB error using the `?` operator.
```rs
fn test() -> anyhow::Result<()> {
let config = Config::default();
let records = vec![];
Collection::build(&config, &records)?;
Ok(())
}
```

feat: add empty impl std error for error

---

py/oasysdb/collection.pyi
src/func/distance.rs
src/tests/test_distance.rs

Please check issue #70 for more information about this PR.
This PR adds a new option `Distance::NormCosine` or in string form, `norm_cosine` that allows a faster calculation of normalized vectors by eliminating calculations of the vector magnitude.
I added a test to the distance calculation result.

feat: add normalized cosine distance

---

.github/workflows/quality-check.yml
Cargo.lock
Cargo.toml
src/func/metadata.rs
src/tests/mod.rs
src/tests/test_metadata.rs

For more information about this PR and what it solves, please check issue #69.
One thing to add is that this interoperability is gated behind the `json` feature.
I added new test suites to test conversions between `Metadata` and `serde_json::Value`.

feat: add conversion from json value to metadata vice versa

---

bench/main.rs

This PR adds a new benchmark function built-in using `criterion` Rust crate to measure the `Collection.true_search` performance.
There's no new feature added.

feat: add collection true search benchmark

---

src/func/vector.rs

This PR adds utility methods to `VectorID` struct:
- `to_u32`: Returns the VectorID as u32.
- `to_usize`: Returns the VectorID as usize.
The functionality is very simple.

feat: add vector id utility methods

---

examples/quickstart.rs
py/tests/test_collection.py
readme.md
src/func/collection.rs
src/func/utils.rs

This PR is to fix the bug in this Google Colab notebook:
https://colab.research.google.com/drive/1zQtpXkkWASt_37aiA7m5ZZcMqBnUGxOZ?usp=sharing
In short, the search result distance returned is that of Euclidean instead of the configured Cosine.
https://github.com/oasysai/oasysdb/blob/b04772b5dc9fc27faab3e2c42a1f39885f9c2628/src/func/collection.rs#L297
https://github.com/oasysai/oasysdb/blob/b04772b5dc9fc27faab3e2c42a1f39885f9c2628/src/func/utils.rs#L337-L349
I added a new test in Python to check the result.

fix: search distance calculation

---

.cargo/config.toml
.github/workflows/quality-check.yml
py/tests/test_database.py
src/tests/mod.rs
src/tests/test_collection.rs
src/tests/test_database.rs

This PR uses single-threaded tests to simplify testing OasysDB persistence. Previously, due to using multi-threaded test, test creators has to essentially create an ID for their test to ensure that different test opens a different database file.

chore: simplify oasysdb test suites

---

bench/main.rs

This PR adds a benchmark to measure the collection insert operation. This is the result I got from running it locally on Apple M2 CPU with 16GB of RAM:
- Collection size: 1,000,000
Vector dimension: 128
Insert performance: 45ms

feat: add insert benchmark

---

Cargo.lock
Cargo.toml
py/oasysdb/database.pyi
py/tests/test_database.py
requirements.txt
src/db/database.rs
src/func/collection.rs
src/func/vector.rs
src/lib.rs
src/tests/test_database.rs

This PR tries to solve the issue mention in issue #79 and discussion #77 where the database size on disk is overly large due repeated saving the collection causing all of the IO buffers to pile up.
This PR adds `flush` and `async_flush` method to the database struct.
Added 2 new tests for both Python and Rust test suites to test the flushes functionalities.

fix: large dirty io buffers with flush

---

Cargo.lock
Cargo.toml
docs/guide.md
docs/migrations/0.4.5-to-0.5.0.md
readme.md
src/db/database.rs
src/db/mod.rs
src/func/err.rs

This PR is purposed to fix the issue #79 by replacing the previous internal implementaion of database methods that directly stored and retrieved serialized vector collections to Sled with writing and reading them from a file.
After talking to the maintainers of Sled, it makes sense that Sled is not built to store `Collection` due to its size reaching 100MB to 10GB per collection. Instead now, OasysDB database serialize and store collections directly into files.
The file reference to where the collection is stored is now packaged in `CollectionRecord` along with other utility details like collection length and time the database is created and updated.
This PR doesn't change how the API works to change the test. But this PR is not compatible with the previous release.

feat: save collection to disk via file write

---

bench/main.rs
bench/utils.rs

This PR adds a new benchmark suite to measure the database performance. Benchmark that are added:
- Save collection to database
- Get collection from database (load the collection to memory)
This PR has no additional functionality. Only benchmarking that can be tested and ran using `cargo bench` command.

chore: add save and get collection bench

---

src/func/utils.rs

This PR fixes a bug that happens when attempting to insert a new vector record to the collection but the collection can't find the first valid vector ID to start the insert operation.
The script below will reproduce the issue with the previous version:
```rs
use oasysdb::prelude::*;
fn main() {
let config = Config::default();
let mut collection = Collection::new(&config);
let record = Record::many_random(1536, 2);
// Insert and delete a record
collection.insert(&record[0]).unwrap();
collection.delete(&VectorID(0)).unwrap();
// Insert another record
collection.insert(&record[1]).unwrap();
}
```

fix: called option unwrap on a none value on insert

---

docs/guide.md
py/oasysdb/collection.pyi
src/func/metadata.rs
src/tests/test_metadata.rs

This PR adds boolean metadata type with its corresponding type conversion to JSON, PyO3, and Rust primitive types.
I added a new test to store a more complex JSON data containing multiple different value types.

feat: add bool metadata

---

src/db/database.rs
src/db/mod.rs

As desribe in issue #98
This PR makes save_collection atomic to prevent corruption in the case of failure.
There is no change in API. So, there is no additional test needed.

fix: atomic collection file writes

---

Cargo.lock
Cargo.toml
examples/measure_recall.rs
src/db/database.rs

Fix an issue that hinder OasysDB to interact with PostgreSQL due to async runtime.
We enable Tokio runtime for SQLx and use Tokio to execute OasysDB async functions.
Using the `measure_recall.rs` example:
1. Change the source database from SQLite to Postgres.
2. Modify some of the SQL queries for SQLite to Postgres.
3. Run the example with successful result.

fix: ensure oasysdb works well with postgres
